### ISSUE TITLE
关于非模式生物富集分析的问题

### ISSUE THREAD

**Issue by chhhhai** [xiayh17/RNAseqStat2#1]
非模式生物使用 eggnog-mapper 注释结果构建 OrgDB（使用 AnnotationForge），然后library(org.My.eg.db, lib.loc = "E:/EC/orf.protein.fa_eggnog/R_Library/")。
命令在进行Enrich GO analysis Start报错
报错信息：
<U+0001F333> Enrich GO analysis Start. This process will take a few minutes.
Error in enhance_get_GO_data(OrgDb, ont, keyType) : 
  keytype is not supported...
In addition: Warning message:
Zero sample variances detected, have been offset away from zero 

能否支持非模式生物富集分析呢？

**Comment by xiayh17** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        有点意思，介意提供一下数据吗？
        不方便发这里可以直接发我邮箱
    
        
            
        
    
    
         
        
            font{
            line-height: 1.6;
        }Best Regards,Yonghe Xia
        
    
     

    在2022年2月16日 ***@***.***> 写道： 




非模式生物使用 eggnog-mapper 注释结果构建 OrgDB（使用 AnnotationForge），然后library(org.My.eg.db, lib.loc = "E:/EC/orf.protein.fa_eggnog/R_Library/")。

命令在进行Enrich GO analysis Start报错

报错信息：

<U+0001F333> Enrich GO analysis Start. This process will take a few minutes.

Error in enhance_get_GO_data(OrgDb, ont, keyType) :

keytype is not supported...

In addition: Warning message:

Zero sample variances detected, have been offset away from zero

能否支持非模式生物富集分析呢？

**Comment by chhhhai** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 有点意思，介意提供一下数据吗？ 不方便发这里可以直接发我邮箱 font{ line-height: 1.6; }Best Regards,Yonghe Xia 在2022年2月16日 ***@***.***> 写道： 非模式生物使用 eggnog-mapper 注释结果构建 OrgDB（使用 AnnotationForge），然后library(org.My.eg.db, lib.loc = "E:/EC/orf.protein.fa_eggnog/R_Library/")。 命令在进行Enrich GO analysis Start报错 报错信息： <U+0001F333> Enrich GO analysis Start. This process will take a few minutes. Error in enhance_get_GO_data(OrgDb, ont, keyType) : keytype is not supported... In addition: Warning message: Zero sample variances detected, have been offset away from zero 能否支持非模式生物富集分析呢？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

请问有收到我私发给您的数据吗？

**Comment by xiayh17** [comment]
> > font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 有点意思，介意提供一下数据吗？ 不方便发这里可以直接发我邮箱 font{ line-height: 1.6; }Best Regards,Yonghe Xia 在2022年2月16日 _**@**_._**> 写道： 非模式生物使用 eggnog-mapper 注释结果构建 OrgDB（使用 AnnotationForge），然后library(org.My.eg.db, lib.loc = "E:/EC/orf.protein.fa_eggnog/R_Library/")。 命令在进行Enrich GO analysis Start报错 报错信息： <U+0001F333> Enrich GO analysis Start. This process will take a few minutes. Error in enhance_get_GO_data(OrgDb, ont, keyType) : keytype is not supported... In addition: Warning message: Zero sample variances detected, have been offset away from zero 能否支持非模式生物富集分析呢？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 请问有收到我私发给您的数据吗？

已经收到
