### ISSUE TITLE
cannot coerce type 'closure' to vector of type 'character'

### ISSUE THREAD

**Issue by 472104ZCD** [xiayh17/RNAseqStat2#2]
Thanks for creating this awesome package. I am using it for the first time and just copy/pasting some code to see how it works and I get an error. Can you help me troubleshoot?

Here is what I pasted in RStudio:
data_o <- runALL(data_i,dir = "testArray",top = 10,parallel = T,GO = T,KEGG = T)
i Your Array will be make a check!
√ Box checking have done, a plot was store in 'testArray/'.
√ Density checking have done, a plot was store in 'testArray/'.
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'

**Comment by xiayh17** [comment]
Is it convenient to provide your complete code and data? You can send it to my personal email address at xiayh17@gmail.com
