### ISSUE TITLE
RNAseqSTAT2报错

### ISSUE THREAD

**Issue by liuxc20160122** [xiayh17/RNAseqStat2#5]
请问下， 夏老师我在使用你在云雀上的非模式生物代码分析RNA转录组分析时，
出现
> KEGG_anno <- eggnogG2T(anno_data,"#query","KEGG_Pathway")
> KEGG_anno <- KEGG_anno %>%
+   filter(stringr::str_detect(Term, 'ko'))
Error in vctrs::vec_size_common(string = string, pattern = pattern, replacement = replacement,  : 
  找不到对象'Term'
怎么解决， 还有我不知道为什么我的GSEA分析不出数据，谢谢

**Comment by xiayh17** [comment]
1. 找不到对象'Term'， 可能是文件格式出现了一些问题，
2. GSEA分析不出数据可能是你的物种在GSEA数据库中没有

从你提供的信息我很难进一步作出准确的回答，因为存在多种可能，最好的办法是把能复现报错的代码发我邮箱

**Comment by liuxc20160122** [comment]
夏老师，你好！
&nbsp;我把code和数据发给你下，你有空可以帮我看下吗，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiayh17/RNAseqStat2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiayh17/RNAseqStat2] RNAseqSTAT2报错 (Issue #5)





  
找不到对象'Term'， 可能是文件格式出现了一些问题，
 
GSEA分析不出数据可能是你的物种在GSEA数据库中没有
  
从你提供的信息我很难进一步作出准确的回答，因为存在多种可能，最好的办法是把能复现报错的代码发我邮箱
